# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-25 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('township', '0002_auto_20170525_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitebanner',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
